### PR TITLE
Change all references to the account number to Account Address

### PR DESCRIPTION
**Pull request by isabellewei**
### Description

The branding team requested that all references to the account number are now `Account Address`.

### Other changes

After the recipients refactor,  there is no display name that would be set to `Mobile #`, updated the logic for displaying text in `ValidateRecipientAccount` accordingly

### Tested

not tested

### CODE REVIEW

**Review by etuleu — APPROVED** [review]

**Review by MuckT — COMMENTED** [review]
It looks like all instances of 'account number' are changed to 'Account Address' irrespective of previous casing. Is this intentional?

**Comment by isabellewei** [comment]
> It looks like all instances of 'account number' are changed to 'Account Address' irrespective of previous casing. Is this intentional?

Yes! I was told Account Address should always be uppercase

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R66](https://valora.testquality.com/project/12128/testcase/295608/requirement/11610).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.17.0 & Test flight build V1.17.0 and updated the status in test quality tool.

**Test quality tool link:**

- **Android:**
   - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450278

    
- **iOS:**
   - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450265


**New Bug:** 

- We have observed that user is able to see "Account No." instead of "Account Address" on Payment transaction screens. Also observed same issue for exchange screen for "Add Funds" & "Cash Out" screen

**FYI:** We have raised bug ticket 921 for above observation
**Verified On Devices:** iPhone SE (14.2), Samsung Galaxy S4 (4.4.2)

CC: @isabellewei

**Pull request merged**
