### PR TITLE
Enable Get Attributes for Android E2E Tests

### PR DESCRIPTION
**Pull request by MuckT**
### Description

This PR adds a dependency to [com.google.android.material:material:1.2.0](https://github.com/material-components/material-components-android/releases/tag/1.2.0) as to enable the detox method [.getAttributes() ](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#getAttributes)on Android devices.

Detox issue: [getAttributes() does not work in detox 18.14.0 in Android #2846](https://github.com/wix/Detox/issues/2846)

### Tested

```Bash
# Able to run `AccountSetup.spec.js`
yarn test:e2e:android -f AccountSetup.spec.js -t "New Account"
```

### How others should test

Observe the above test in CI & run locally 

### Backwards compatibility

Needs Review

### CODE REVIEW

**Review by jeanregisser — COMMENTED** [review]
PR description doesn't match the changes.
The explicit dependency is not needed then?

**Comment by etuleu** [comment]
Nice usage of the -t flag :)

**Comment by MuckT** [comment]
@jeanregisser based on [this link](https://github.com/wix/Detox/issues/2846) shared the dependency is needed to allow getAttributes() to work on Android. Detox might fix this and at such time we can remove the explicit dependency.

**Comment by etuleu** [comment]
> @jeanregisser based on [this link](https://github.com/wix/Detox/issues/2846) shared the dependency is needed to allow getAttributes() to work on Android. Detox might fix this and at such time we can remove dependency.

I think you maybe forgot to add some files to the PR?
The only change we see is basically in the test file, nothing about dependencies.

**Comment by MuckT** [comment]
@etuleu & @jeanregisser was looking at [this commit](https://github.com/celo-org/wallet/pull/877/commits/a0064715a4de55b0f841eb2363b88286c95da395) which appears to add an android dependency.

**Review by etuleu — APPROVED** [review]
Make sure you add the gradle dependency that was reverted by mistake

**Pull request merged**
