### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by celo-bot-crowdin**

### CODE REVIEW

**Review by aleksey-nov — APPROVED** [review]

**Comment by Celoqa** [comment]
HI @MuckT Can you please let us know we need to test anything in this task.
Thanks!

**Comment by MuckT** [comment]
@Celoqa a manual review of the changed strings to check for overlap of elements should be sufficient to test this task. No functional changes were made so reviewing this should just entail running through the onboarding flow in Spanish and Portuguese.

**Comment by Celoqa** [comment]
Hi @MuckT thanks for giving information.
we will test & update task for the same.

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issues on latest builds Android internal build V1.16.1 & Testflight build V1.16.1(67) and observe the followings.
- "Connecting banner is overlapped with “Espanol..” text when user as bad connection
- "Connecting banner is overlapped with “Portuges.. ” text when user as bad connection
- We have updated existing issue for above mentioned points #559 
- **"Existing issue:"** https://github.com/celo-org/celo-monorepo/issues/6444
- Everything is working fine without any overlaps when running through the onboarding flow in Spanish and Portuguese.
Also we have observed that user directly redirects to home page when trying to verify phone number in 4os device.
Raised a query ticket for the same https://github.com/celo-org/wallet/issues/878

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issues on latest builds Android internal build V1.16.0 in Android 11 OS & observed the followings:

- "Connecting banner is overlapped with “Espanol..” text when user as bad connection
- "Connecting banner is overlapped with “Portuges.. ” text when user as bad connection
- We have updated existing issue for above mentioned points in [Language selection overlaps with "Connecting..." banner on Welcome onboarding screen #559](https://github.com/celo-org/wallet/issues/559)

**Pull request merged**
