### PR TITLE
Increase the default transaction limit from $500 to $1000

### LINKED ISSUE #151: Increase $500 Daily limit to $1000 in App
Background: We have approval to increase the daily limit.

### Expected Behavior

Daily Transfer + Exchange limit increases from 500 -> 1000
No change to cash in limit + other limits in app that are not set at $500/day.

cc @dominiquejane @denisse as we will need to update FAQ + support articles

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Increase the daily transaction limit to $1000 for non-KYC'ed users.

### Other changes
N/A

### Tested
Yes

### Related issues
- Fixes #151 

### Backwards compatibility
Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
Looks great! 👌 I also need to change this default on the admin dashboard.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @gnardini  can we get Alfajore test net Android and IOS build to test transaction limit. 

Currently , we can see v1.12 Alfajores build not v1.13.

**Comment by tarikbellamine** [comment]
@etuleu should have this updated for you now :)

**Comment by Celoqa** [comment]
Thank you @tarikbellamine for update. Sure we will update our observations when we will get latest Alfajores build from @etuleu

**Comment by Celoqa** [comment]
Hey @tarikbellamine I have verified this issue using Alfajores build V1.14.2(61) for iOS & V1.14.1 for Android & observed following:
**Observations:**

- [x]It is observed that, Non-KYC User is able to see $1000 as Daily Send Limit on "Account Send Limit" page

**Verified On Devices:** iPhone SE (14.2), Redmi Note 8 (9.0)
**Attachment:** [$1000DailyLimitForNon-KYCUser.jpg](https://drive.google.com/file/d/1G64_vPMGAVEB4MiP4rEJvZUlkBJRtl9j/view?usp=sharing)
Thanks..!!

**Pull request merged**
