### PR TITLE
Add section about Branding to README

### PR DESCRIPTION
**Pull request by isabellewei**

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Yeah, thanks for adding!! 💯

**Comment by Celoqa** [comment]
Hey @isabellewei Can you please let us know what we need to test here from front end as well as back end side from our end ?
Thanks..!!

**Comment by MuckT** [comment]
@Celoqa I've confirmed the branding section is updated in the [README.md](https://github.com/celo-org/wallet/blob/main/packages/mobile/README.md#branding-for-valora-employees-only) and that the branding repo is working as intended. No need for additional testing.

**Comment by Celoqa** [comment]
Thanks @MuckT or the update.

**Pull request merged**
