### PR TITLE
[WalletConnect] implement personal_decrypt

### PR DESCRIPTION
**Pull request by eelanagaraj**
### Description
- implements `personal_decrypt` acceptRequest handling
- modifies data screen for `personal_decrypt` to display the hex data that is to be decrypted

### Other changes
- moves `unlockAccount` to before the specific method handling -- this will need to be called for all methods we implement, and the feeling as a user doesn't change too perceptibly (only slight difference would be that a user would be prompted to unlock even for an unimplemented method, but they would still see + click the allow and it would fail silently (from Valora's perspective) with/without this change)

### Tested
Manually by extending the run-in-memory-client.ts script in the celo-monorepo in [this PR](https://github.com/celo-org/celo-monorepo/pull/8037)

### Related issues
Closes celo-org/celo-monorepo#7515

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by Celoqa** [comment]
Hey @MuckT Can you please let us know if we need to test anything here from our end ?
Thanks..!!

**Comment by MuckT** [comment]
@eelanagaraj are there steps to manually test this change?

**Comment by eelanagaraj** [comment]
Hey @MuckT, this one is a bit tricky but I think it's easiest to test this using the script below in the `celo-monorepo`.
- since the script uses a private key, create a test private key and restore Valora with this account (so you can use the PK to encrypt the message)
- Use the script `packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-client.ts`. Uncomment the `decryptMessage` flow and then run the client; copy and paste the QR code that it provides into Valora's QR code reader, and provide the test private key to the client in the CLI when prompted. Ensure that it termiantes without an error (as it also checks that it decrypts the message properly in the client).
Hope that makes sense, let me know if you have any questions here!

**Pull request merged**
