### PR TITLE
Fixed the blockscout query parameter type

### PR DESCRIPTION
**Pull request by carterqw2**
### Description

The argument parameter was incorrect as according to the doc it should be `AddressHash`. The new version of blockscout is stricter and validates it.

### Tested

Tested on rc1.

### How others should test

Copy the whole query and test it on the graphql page of blockscout https://explorer.celo.org/graphiql.

### Related issues

n/a

### Backwards compatibility

Yes.

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by Celoqa** [comment]
Hi @jeanregisser @carterqw2  Can you please let us know if we need to test anything in this if yes can you provide more information.
Thanks!

**Comment by carterqw2** [comment]
No need to test, thanks.

**Comment by Celoqa** [comment]
Thanks @carterqw2  or the update.

**Pull request merged**
