### PR TITLE
Modify notification service to support cEUR

### PR DESCRIPTION
**Pull request by eruizgar91**
### Description

Add support to cEUR in the notification service, to populate firebase with the cEUR/cGLD exchange rates.

### Other changes

N/A

### Tested

Tested in alfajores;

### How others should test

N/A

### Related issues

-  https://github.com/celo-org/wallet/issues/230

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Thanks, can you please update the PR description so it shows actual info instead of the default template?

**Comment by eruizgar91** [comment]
@jeanregisser updated

**Review by gnardini — APPROVED** [review]
Great job on this!

We're storing both `cUSD/CGLD` and `cGLD/cUSD` conversion but only `cGLD/cUSD` is used. Not the end of the world and this was present before your PR but it is a bit wasteful imo. Up to you if you want to remove the reverses (`cUSD/cGLD` and `cEUR/cGLD`) or not.

We also need to add push notification support for cEUR, but I guess that can be done in another PR.

**Comment by jeanregisser** [comment]
> We're storing both `cUSD/CGLD` and `cGLD/cUSD` conversion but only `cGLD/cUSD` is used. Not the end of the world and this was present before your PR but it is a bit wasteful imo. Up to you if you want to remove the reverses (`cUSD/cGLD` and `cEUR/cGLD`) or not.

`blockchain-api` and hence the wallet transaction feed uses both for currency conversion: https://github.com/celo-org/wallet/blob/9ae1b0bba7b213b310dc8043536abd1163534ed8/packages/blockchain-api/src/currencyConversion/GoldExchangeRateAPI.ts#L59
What was changed here is correct.

**Comment by jeanregisser** [comment]
> @jeanregisser updated

I still see default strings from the template. Please use `N/A` instead 🙏

**Comment by gnardini** [comment]
> `blockchain-api` and hence the wallet transaction feed uses both for currency conversion

I see, thanks for pointing that out. It still feels unnecessary since one exchange rate is basically `1 / the other`, so storing just one should be enough. Definitely not a priority though, it looks like there are some TODOs related to caching in the `blockchain-api` too so we can group these two things together if we ever need to improve performance there.

**Comment by jeanregisser** [comment]
> I see, thanks for pointing that out. It still feels unnecessary since one exchange rate is basically `1 / the other`, so storing just one should be enough. Definitely not a priority though, it looks like there are some TODOs related to caching in the `blockchain-api` too so we can group these two things together if we ever need to improve performance there.

I forgot the exact details, I believe @annakaz did it this way because it's not always `1 / the other`.
Though it's likely the app does use this shortcut in some places. Might be worth checking what is right.

**Comment by Celoqa** [comment]
Hey @MuckT  @tarikbellamine Currently we have Alfajores Build V1.14.3(62) for iOS and V1.14.1 for Android. And as of now we are only able to see cUSD as currency and not found cEUR support.
Can you please provide us latest Alfajores Build for both Android as well as iOS so that we can test it from our end 
Thanks..!!

**Pull request merged**
