### PR TITLE
Re-enable Transak

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Re-enable Transak.

### Other changes
N/A

### Tested
Yes

### Related issues
N/A

### Backwards compatibility
Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
🚀

**Comment by Lss-Ankit** [comment]
@etuleu @tarikbellamine  Verified task using Android internal build V1.13.0(1004294348 | Test Flight build V1.13.0(55) and found that we are blocked to verify task due to issue https://github.com/celo-org/wallet/issues/262.

**Comment by tarikbellamine** [comment]
Thanks @Lss-Ankit issue #262 should be closed now.

**Comment by Celoqa** [comment]
Hey @tarikbellamine yes now Transak screen get loaded completely.
Here are my observations:

- [X] User redirect to "global.transak.com" page after tapping on Transak from Add Funds screen.

- [ ] BTC, XRP, BNB disaled untill 23rd April blue banner is displaying

- [ ] Also it is observed that "Card payment option is not available in your country. Please go back and select different payment method" error message displayed after confirming order using US phone number. [Attachment](https://drive.google.com/file/d/1qG_Pvt_McYT1J9pxa0CYvE6m-reFD0nJ/view?usp=sharing)

- [ ] Also it is observed that nothing happens when user try to change country as well as Network. [Attachment](https://drive.google.com/file/d/1NgHI4pSplBniViPoEuwPE64tKJ7Sy88c/view?usp=sharing)

Let me know needful for above observations. Also let me know if anything need to test here.
Thanks..!!

**Pull request merged**
