### PR TITLE
Add cEUR to Add/Withdraw screen

### LINKED ISSUE #217: Add cEUR to Add and withdraw screen

### PR DESCRIPTION
**Pull request by isabellewei**
### Description

Adds `cEUR` option to `Add/Withdraw` screen, disabled for now as we have no cEUR cash in/cash out providers

### Tested

tested on physical Android

### How others should test

- go to `Add/Withdraw` from the Hamburger menu
- go to `Add Funds`
- verify that `cEUR` option is there, and is always disabled

### Related issues

- Fixes #217 

### Backwards compatibility

yes

### CODE REVIEW

**Review by gnardini — COMMENTED** [review]
Would you mind attaching a screenshot of what this looks like?

**Comment by isabellewei** [comment]
Screenshot_20210507-161144_Alfajores (dev)
Screenshot_20210507-161136_Alfajores (dev)

**Comment by gnardini** [comment]
Amazing! Thanks for the screenshot. So, this looks good but it's pointed to main and has all the changes of the other PR, so I'll approve once that one is merged since this will merge unapproved changes otherwise 😅 

If you want to help out with speeding up that process you can leave a review there: https://github.com/celo-org/wallet/pull/318

**Review by gnardini — APPROVED** [review]

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R41](https://valora.testquality.com/project/12128/testcase/287391/requirement/11468).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest android build V1.16.1 & Testflight build V1.16.1(67) and updated the status in testqulaity tool.

**Testquality tool link:**

**Android:**
- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432165

**iOS:**
- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432193

**Devices:** Vivo v11 pro (10), iPhone 6+(12.4.5)

CC: @isabellewei

**Comment by Celoqa** [comment]
Hi @MuckT, We have verified this issue on Latest android build V1.16.0 in Android 11.0 OS and everything is working as expected.
**Device Details:** Google Pixel 4a(11.0)

**Pull request merged**
