### PR TITLE
Update text of RaiseLimitScreen

### LINKED ISSUE #407: Update text of RaiseLimitScreen
### Current behavior
The description text in the `RaiseLimitScreen` is flipped for verified and unverified users.

### Desired behavior
Correct texts

### PR DESCRIPTION
**Pull request by gnardini**
### Description

The description text in the `RaiseLimitScreen` was flipped for verified and unverified users. Not it isn't

Screen Shot 2021-05-26 at 17 32 01

Screen Shot 2021-05-26 at 17 31 45

### Other changes

N/A

### Tested

Manually, went to the screen (see screenshots)

### How others should test

Go to the raise limit screen and check that the text there makes sense with your verification status.

### Related issues

- Fixes #407

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Thanks! 
I'm wondering if we should rename the remote flag so we can enable it only once this fix makes it to a new release. What do you think?

**Comment by gnardini** [comment]
Good idea, renamed the flag

**Comment by Celoqa** [comment]
Hey @gnardini Can you please provide us latest Alfajores build for Android & iOS ?
We are able to see flipped text in old Alfajores builds i.e. V1.14.1 (for Android) & V1.14.3(for iOS)
**FYI:** We are not able to see "Raise Accound Send Limit" option in latest Android internal build and Test Flight V1.15.0
**Attachment:** [TextForNon-Verified.png](https://drive.google.com/file/d/1dvEbk7bJsUBHp-XjiAMJECUik474XtUx/view?usp=sharing)
[TextForVerifiedUser](https://drive.google.com/file/d/1rH7Ao3DpZNYhQ0t_CLcOZwWLwNO8D_B1/view?usp=sharing)
**Verified On Devices:** Redmi Note 8 (9.0), iPhone SE (14.2)
Thanks..!!

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R35](https://valora.testquality.com/project/12128/testcase/286106/requirement/11368). Do not remove or edit.

**Pull request merged**
