### PR TITLE
Add Bitfy and FlowBTC as providers for Brazil

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Added two new cash in/out providers for Brazil. These integrations are just a link to a WebView for those providers like the ones we have for Ponto and Kotani.

### Other changes

N/A

### Tested

Manually by using a  BR number (and checking it doesn't show up for other countries)

### Related issues

- Fixes #7449

### Backwards compatibility

N/A

### CODE REVIEW

**Review by tarikbellamine — APPROVED** [review]
Nice work given the time crunch! Eventually, we may want to revisit our strategy for remote enabling providers and potentially restructure this a bit :)

**Comment by Celoqa** [comment]
Hi @tarikbellamine I have tried to verify this issue using Android Internal Build V1.12.0(1004294340) & Test flight build V1.12.0(49) & observed following.
**Observations:**

- Non-verified Brazil user not able to see "Bitfy and FlowBTC" providers.

- Also it is observed that, start button not get enabled even user entered correct Brazil number while confirming phone number. Start button only enabled after entering 55 two times. Hence, we blocked to verify this issue by verifying phone number. Please refer attachment.
**Attachment:** [UserNotProceedForBrazilNumber.mp4](https://drive.google.com/file/d/1U2DXovj9205TCA3Rx3gMc8ZK46b9y9q0/view?usp=sharing)
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR (14.2)

Let me please know if anything need to test.

**Comment by gnardini** [comment]
@Celoqa It's not necessary to verify the Brazilian number, after putting it in like you did you should see Bitfy and FlowBTC.

**Comment by Celoqa** [comment]
Hey @gnardini I have verified this issue  & observed following:
**Observations:**

- [x] We are able to see Bitfy and FlowBTC providers for Alfrajos Wallet (49) version in iOS.

**Attachment:** [BitfyAndFlowBTCOnlyForAlfajoresVersion.png](https://drive.google.com/file/d/19VykcrIjFhs-fUqNzUwEaV2lWU_1Ic2X/view?usp=sharing)

- [ ] As of now we not able to see Alfrajos version for android. Will update for android when we will receive this version.

- [ ] We are not able to see same for Mainnet version for both android as well as iOS.

**Comment by Celoqa** [comment]
Hey @gnardini Can you please let us know if any updates for Android Alfrajos version so that we can test UI changes for android also.
Thanks..!!

**Comment by gnardini** [comment]
Hi @Celoqa!
The alfajores version should be available on the Play Store. It's under the name `Celo Alfajores Wallet - TEST ONLY`. The version is 12.0.1. Let me know if you can't see it!

**Comment by Celoqa** [comment]
Hi @gnardini 
We are able to see **Celo Alfajores Wallet - TEST ONLY**. The version is 1.9.0 not able to see 12.0.1? 
Can you please do the needful.

**Pull request merged**
