### PR TITLE
[Wallet] Adjust integration

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This PR adds the Adjust SDK via Segment for tracking install attributions from ad campaigns.

### Other changes

- Upgraded all analytics dependencies.
- Clean-up the `secrets.json` file to avoid duplicating configs between networks.
  - Specifically all alfajores builds now use a different `SEGMENT_API_KEY` than mainnet. Up until now that wasn't the case. All analytics were going to the same Segment source.

### Tested

Couldn't test the full attribution flow with the Adjust dashboard, but checked the SDK is configured correctly and events are sent.

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/6635

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
> Specifically all alfajores builds now use a different SEGMENT_API_KEY than mainnet. Up until now that wasn't the case. All analytics were going to the same Segment source.

😱

**Comment by Celoqa** [comment]
Hey @jeanregisser , @gnardini Could you please let us know if anything need to test here from backend as well as front end from our side ?

**Comment by Celoqa** [comment]
Hey @jeanregisser Let me please know if any updates for above comment.

**Comment by Celoqa** [comment]
Hi @gnardini thanks for the confirmation.

**Pull request merged**
