### PR TITLE
Make unencrypted comment warning text more visible

### PR DESCRIPTION
**Pull request by nategraf**
### Description

@gtank and I noticed that its way too easy to miss the the warning that a comment is being senty
publically in the clear. As a remedy, this PR makes the fairly simple change if making the warning
text `colors.warning` (red) and slightly larger.

Screenshot_before Screenshot_after 

### Tested

Navigated to the send flow with a valid addrss that is not registered on Alfajores and entered a
comment. Observed that the warning text had changed.

### How others should test

Navigate to the send flow with a valid addrss that is not registered on Alfajores. Check that the
warning text has chnaged.

### Backwards compatibility

No backwards compatibility concerns

### Related issues

* https://github.com/celo-org/wallet/issues/61
* https://github.com/celo-org/wallet/issues/205

### CODE REVIEW

**Comment by nategraf** [comment]
@jeanregisser @coreycelo What do you think of this change?

**Comment by coreycelo** [comment]
Improving visibility is a good goal, but I'm not sure it's an error per se and the red makes it seem that way. I could see that distinction (whether it's an error) being dependent on the user group we're optimizing for though. Obviously the ideal solution is we encrypt all comments, particularly if we think that's important philosophically or to our particular demographic.

cc @aleksey-nov

**Comment by nategraf** [comment]
Right it is not an error, but I would consider it a warning. (i.e. We are warning the user that any comments they are making will be public, which is different than the expectation). In any case, the current message is not visible enough such that users are currently likely to submit a comment they would assume is private, and would be surprised to find out is public.

**Comment by coreycelo** [comment]
Let's swap to our "informational" blue instead—unsure if this color exists already as a reusable defined color in our styles/components, but the hex is #0768AE

**Comment by nategraf** [comment]
@coreycelo I went ahead and made the change from red to blue. Let me know if it looks good to you.

**Review by coreycelo — APPROVED** [review]
Looks good!

**Review by jeanregisser — APPROVED** [review]
Thanks!! Ship it 🎉

**Pull request merged**
