### PR TITLE
Merge main into "Verification Refactoring - Part #2"

### PR DESCRIPTION
**Pull request by etuleu**
### Description

Trying to merge Ivan's verification refactor PR (https://github.com/celo-org/wallet/pull/116). First step is this which merges main into it.

I branched off of https://github.com/celo-org/wallet/tree/i1skn/refactor-verification so I can merge main into it.

There were quite a few conflicts and I went through all of them manually and made sure we catch the fixes that were done in main since. Of course it's possible I missed some of made the wrong merge resolution so please review carefully.

We should also go through all the verification fixes that were done on main since this PR was opened to see if they are incorporated correctly.

### Other changes

None

### Tested

Not yet on this particular PR but I've been doing testing both manual and wrote some new unit tests on a separate PR which I will follow up with once this one is merged in order to keep changes cleaner.

The goal is to also write some end to end tests for verification.

### How others should test

All verification tests, especially the ones we discovered recently such as inputting 2 codes quickly (before the first one is verified), and inputting the same code twice. 

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

Yes.

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
Thanks for pushing this forward! 🚀 

I've tested it manually and have been able to verify successfully every time. There are some UI glitches to fix, but they are not caused by this PR, they were pre-existing, I'll work on those in a different PR

**Comment by Celoqa** [comment]
Hi @tarikbellamine @i1skn We have verified this on latest Android internal build V1.15.0 & Testflight build V1.15.0(63) and observe the followings:

**Verification flow with create new account:**
- [ ] User is able to complete the verification flow without any issues while auto pasting the codes. 
- [ ] User is able to Resend the codes & complete the verification flow without any gaps.

**Verification flow with Restore account key:**

- [ ] User is able to complete the verification flow without any issues while auto pasting the codes. 
- [ ] User is able to Resend the codes & complete the verification flow without any gaps.

**Restore account with already verified number:**

- [ ] User directly redirects to home Connect contacts page when try to restore account with already verified number

**Issue:**

- [ ] First & Second code fields are shown blank when user ungraded to V1.14-V1.15 given below are the steps to repro issue:

  - Install V1.14 build 
  - Paste only first & second fields Keep third code as blank then skip the verification
  - Make sure user should able to see first & second codes when resume on V1.14 build
  - Upgrade it to V1.15 & go to verification flow
  - Observe First & second fields are shown blank.
[Attachment](https://drive.google.com/file/d/1EI8fygqbfTj4jNEb_GX5SLiDhny5qZ4r/view?usp=sharing)

**Note:** Also we have tried edge cases and works fine & we will update this ticket if we found any minor issues after running Regression in V1.15.0

**Comment by i1skn** [comment]
I'm happy, that this PR was merged after all!!! @etuleu 👍🏻

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R31](https://valora.testquality.com/project/12128/testcase/286100/requirement/11364). Do not remove or edit.

**Pull request merged**
