### PR TITLE
Upgrade firebase packages to 11.0.0

### LINKED ISSUE #103: ANR while app in background
### Expected Behavior

Application should not throw ApplicationNotResponding ever.

### Current Behavior

On Android 8+ the app sometimes throws ANRs in response to push notifications while the app is in background.

Example sentry crash: https://sentry.io/organizations/celo/discover/celo-mobile:84f1b697fc8045fc9694cd08c3b1ee19/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1250733&query=ApplicationNotResponding&sort=-timestamp&statsPeriod=7d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

### PR DESCRIPTION
**Pull request by etuleu**
### Description

We need the latest version of the firebase cloud messaging library in order to fix the push notifications while the app is in the background. Currently the app starts in the background and causes ANRs sometimes. With the latest version of the library the app respects the background check. This affects Android devices running version 8 and up.

Example sentry crash: https://sentry.io/organizations/celo/discover/celo-mobile:84f1b697fc8045fc9694cd08c3b1ee19/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1250733&query=ApplicationNotResponding&sort=-timestamp&statsPeriod=7d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

The app still starts but only in a limited mode, in a light receiver, so no react components, which doesn't do much other than checking for foreground / background: https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingReceiver.java

### Other changes

Some callback removal changes happened in the firebase database api related to the removal of the callback (the off function).

I also removed a leftover service definition from the AndroidManifest. I am not sure whether that was affecting anything but it's not needed since firebase version 6.

I also upgraded all packages because they depend on each other.

### Tested

Manually using the push.sh script and looking at logcat logs to make sure the app does not start.
I still need to do more testing to make sure upgrading all the other packages does not break anything.

### Related issues

- Fixes #103 

### Backwards compatibility

Yes.

### CODE REVIEW

**Review by gnardini — COMMENTED** [review]
Awesome to have the updated packages!

I think you need to run `pod install` on the ios repo (or just the `yarn build:wallet` from root) to update the Podfile with the new Firebase versions. Other than that, everything looks good to me :)

**Review by jeanregisser — COMMENTED** [review]
Awesome!
Did you check we don't need the patch anymore? It was necessary on iOS and I unfortunately didn't propose a PR upstream when I did it.

**Comment by etuleu** [comment]
> Awesome!
> Did you check we don't need the patch anymore? It was necessary on iOS and I unfortunately didn't propose a PR upstream when I did it.

Yes I looked at the files and they have similar code. Not exactly the same but I think the same idea.

**Review by jeanregisser — APPROVED** [review]
Nice!
If it doesn't crash on iOS we're good then 👍

**Comment by Celoqa** [comment]
Hi @etuleu  Can you please let us know if anything need to test here from our side ?

**Comment by Celoqa** [comment]
Hey @etuleu Let me please know if any updates for above comment.
Thanks..!!

**Comment by gnardini** [comment]
Hi @Celoqa. There's nothing specific here to test, thank you!

**Comment by Celoqa** [comment]
Hi @gnardini thanks for the confirmation.

**Pull request merged**
