### PR TITLE
Add UI for invite rewards

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Prepare some UI changes for invite rewards. This will be disabled initially, but we'll be able to enable it using a feature flag on Firebase.

The PR is not as big as the number of lines might indicate, 800+ come from a new snapshot file for the `Send` screen.

Screen Shot 2021-03-01 at 16 00 44

### Tested

Manually and added unit tests.

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/7035

### Backwards compatibility

N/A

### CODE REVIEW

**Review by etuleu — APPROVED** [review]
This is awesome!

**Review by etuleu — APPROVED** [review]
There is still a wallet test failing but I think you just have to update the snapshots

**Comment by Celoqa** [comment]
Hi @i1skn we have verified this task using latest Android Internal Build V1.12.0(1004294340) & Test flight build V1.12.0(49) and observe the following.
- We are not able to see the above mentioned UI changes for Invite rewards

Can you please Enable feature flag on Firebase so, we can test this task.
Thanks!

**Comment by i1skn** [comment]
@gnardini can you please take a look on the comment above? Thanks!

**Comment by gnardini** [comment]
These changes are not live yet on the mainnet version of the app, they will be enabled at a later date remotely via Firebase config.

For now, these changes can be seen and tested in the Alfajores version of the app.

**Comment by Celoqa** [comment]
Thanks @gnardini for the information we will verify this changes in Alfajores build and get back to you with an update.

**Comment by Celoqa** [comment]
Hi @gnardini We have verified this task on latest Testflight alfajores build 1.12.0(49) and observe the following.

- Able to see the new UI for invite rewards on send page.

**Device:** iPhone 6+ (12.4.5).
**Build:** Testflight alfajores build 1.12.0(49)

Can you please provide us latest android alfajores build so, we can test this new UI changes on android & let us know if we need to test any other things in this task.
Thanks!

**Pull request merged**
